name: lint

on: push

jobs:
  textlint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install
      - run: chmod +x ./node_modules/.bin/textlint
      - run: npm run lint
